language: android
dist: trusty

env:
  matrix:
    - ANDROID_TARGET=android-25
    - ANDROID_TARGET=android-29
  global:
    - ADB_INSTALL_TIMEOUT=8


android:
  components:
    - build-tools-29.0.2
    - android-29

before_script:
  - chmod +x gradlew      # Grant permissions
  - android list targets
  # Create AVD for given api
  - echo no | android create avd --force --name test --target $ANDROID_TARGET


script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - android-wait-for-emulator
  - adb devices
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
