language: android
dist: trusty

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=5


android:
  components:
    - build-tools-29.0.2
    - android-29

script:
  - adb devices
  - ./gradlew clean assembleDebug assembleRelease testDebug
  - ./gradlew build jacocoTestReport

after_success:
  — bash <(curl -s https://codecov.io/bash)
