language: android
dist: trusty

env:
  matrix:
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-28 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=8


android:
  components:
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository
    - extra-google-m2repository
    - $ANDROID_TARGET
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

before_script:
  - chmod +x gradlew      # Grant permissions
  - android list targets
  # Create AVD for given api
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI


script:
  - ./gradlew build
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - android-wait-for-emulator
  - adb devices
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
