language: android
dist: trusty

env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-29 ANDROID_ABI=armeabi-v7a
  global:
    - ADB_INSTALL_TIMEOUT=8


android:
  components:
    - build-tools-29.0.2
    - android-29

before_script:
  - chmod +x gradlew      #Grant permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
